import { VertexAI } from '@google-cloud/vertexai';
import type { KlineRow } from '../types.js';
import { logger } from '../core/logger.js';

const log = logger.child({ module: 'gemini' });

const project = process.env.BIGQUERY_PROJECT_ID ?? 'project-513b86da-a04a-494a-8e9';
const location = 'us-central1';

export async function generateGeminiReasoning(
  symbol: string,
  klines: KlineRow[],
  ticker: { lastPrice: number; priceChangePercent: number },
  signal: { compositeScore: number; regime?: string | null }
): Promise<string> {
  // Check if API key or project is configured
  if (!process.env.GOOGLE_APPLICATION_CREDENTIALS && !process.env.K_SERVICE && !process.env.BIGQUERY_PROJECT_ID) {
    log.debug('Google credentials/project not configured. Skipping Gemini reasoning.');
    return 'Gemini credentials not configured.';
  }

  try {
    const vertexAI = new VertexAI({ project, location });
    const generativeModel = vertexAI.getGenerativeModel({
      model: 'gemini-3.1-pro',
    });

    const recentCloses = klines.slice(0, 10).map(k => k.close).join(', ');

    const prompt = `Analyze the current market state for ${symbol}.
Context details:
- Recent close prices (last 10 hours, newest first): [${recentCloses}]
- Current Price: $${ticker.lastPrice}
- Price Change (24h): ${ticker.priceChangePercent}%
- Technical Indicator Scores:
  * Composite Score: ${signal.compositeScore}
  * Market Regime: ${signal.regime ?? 'unknown'}

Provide a concise, 1-2 sentence professional trading reasoning for the predicted trend direction (whether bullish, bearish, or neutral). Keep it professional and technical.`;

    const response = await generativeModel.generateContent({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
    });

    const responseText = response.response.candidates?.[0]?.content?.parts?.[0]?.text;
    return responseText?.trim() ?? 'No reasoning generated by Gemini.';
  } catch (err) {
    log.warn(`Gemini reasoning generation failed for ${symbol}`, { error: String(err) });
    return `Gemini analysis failed: ${err instanceof Error ? err.message : String(err)}`;
  }
}
