import {
  mean,
  median,
  mode,
  sum,
  min,
  max,
  sampleVariance,
  variance,
  sampleStandardDeviation,
  standardDeviation,
  sampleCorrelation,
  sampleCovariance,
  linearRegression,
  linearRegressionLine,
  rSquared,
  quantile,
  zScore,
  medianAbsoluteDeviation,
  weightedQuantile,
} from 'simple-statistics';

export {
  mean,
  median,
  mode,
  sum,
  min,
  max,
  sampleVariance,
  variance,
  sampleStandardDeviation,
  standardDeviation,
  sampleCorrelation,
  sampleCovariance,
  linearRegression,
  linearRegressionLine,
  rSquared,
  quantile,
  zScore,
  medianAbsoluteDeviation,
  weightedQuantile,
};

export { Matrix, EigenvalueDecomposition } from 'ml-matrix';
